import type { Favorite } from '../shared/content'

export default [
  {
    kind: 'film',
    title: { ru: 'Фильм 1', en: 'Film 1' },
    author: { ru: 'Автор 1', en: 'Author 1' },
    year: 1975,
    cover: '/demo.webp',
  },
  {
    kind: 'film',
    title: { ru: 'Фильм 7', en: 'Film 7' },
    author: { ru: 'Автор 7', en: 'Author 7' },
    year: 2005,
    cover: '/demo.webp',
  },
  {
    kind: 'film',
    title: { ru: 'Фильм 2', en: 'Film 2' },
    author: { ru: 'Автор 2', en: 'Author 2' },
    year: 1980,
    cover: '/demo.webp',
  },
  {
    kind: 'film',
    title: { ru: 'Фильм 3', en: 'Film 3' },
    author: { ru: 'Автор 3', en: 'Author 3' },
    year: 1985,
    cover: '/demo.webp',
  },
  {
    kind: 'film',
    title: { ru: 'Фильм 4', en: 'Film 4' },
    author: { ru: 'Автор 4', en: 'Author 4' },
    year: 1990,
    cover: '/demo.webp',
  },
  {
    kind: 'film',
    title: { ru: 'Фильм 5', en: 'Film 5' },
    author: { ru: 'Автор 5', en: 'Author 5' },
    year: 1995,
    cover: '/demo.webp',
  },
  {
    kind: 'film',
    title: { ru: 'Фильм 6', en: 'Film 6' },
    author: { ru: 'Автор 6', en: 'Author 6' },
    year: 2000,
    cover: '/demo.webp',
  },
  {
    kind: 'film',
    title: { ru: 'Фильм 8', en: 'Film 8' },
    author: { ru: 'Автор 8', en: 'Author 8' },
    year: 2010,
    cover: '/demo.webp',
  },
  {
    kind: 'music',
    title: { ru: 'Альбом 1', en: 'Album 1' },
    author: { ru: 'Автор 1', en: 'Author 1' },
    year: 1975,
    cover: '/demo.webp',
  },
  {
    kind: 'music',
    title: { ru: 'Альбом 2', en: 'Album 2' },
    author: { ru: 'Автор 2', en: 'Author 2' },
    year: 1980,
    cover: '/demo.webp',
  },
  {
    kind: 'music',
    title: { ru: 'Альбом 3', en: 'Album 3' },
    author: { ru: 'Автор 3', en: 'Author 3' },
    year: 1985,
    cover: '/demo.webp',
  },
  {
    kind: 'music',
    title: { ru: 'Альбом 4', en: 'Album 4' },
    author: { ru: 'Автор 4', en: 'Author 4' },
    year: 1990,
    cover: '/demo.webp',
  },
  {
    kind: 'music',
    title: { ru: 'Альбом 5', en: 'Album 5' },
    author: { ru: 'Автор 5', en: 'Author 5' },
    year: 1995,
    cover: '/demo.webp',
  },
  {
    kind: 'music',
    title: { ru: 'Альбом 6', en: 'Album 6' },
    author: { ru: 'Автор 6', en: 'Author 6' },
    year: 2000,
    cover: '/demo.webp',
  },
  {
    kind: 'music',
    title: { ru: 'Альбом 7', en: 'Album 7' },
    author: { ru: 'Автор 7', en: 'Author 7' },
    year: 2005,
    cover: '/demo.webp',
  },
  {
    kind: 'music',
    title: { ru: 'Альбом 8', en: 'Album 8' },
    author: { ru: 'Автор 8', en: 'Author 8' },
    year: 2010,
    cover: '/demo.webp',
  },
  {
    kind: 'game',
    title: { ru: 'Игра 1', en: 'Game 1' },
    author: { ru: 'Автор 1', en: 'Author 1' },
    year: 1975,
    cover: '/demo.webp',
  },
  {
    kind: 'game',
    title: { ru: 'Игра 2', en: 'Game 2' },
    author: { ru: 'Автор 2', en: 'Author 2' },
    year: 1980,
    cover: '/demo.webp',
  },
  {
    kind: 'game',
    title: { ru: 'Игра 3', en: 'Game 3' },
    author: { ru: 'Автор 3', en: 'Author 3' },
    year: 1985,
    cover: '/demo.webp',
  },
  {
    kind: 'game',
    title: { ru: 'Игра 4', en: 'Game 4' },
    author: { ru: 'Автор 4', en: 'Author 4' },
    year: 1990,
    cover: '/demo.webp',
  },
  {
    kind: 'game',
    title: { ru: 'Игра 5', en: 'Game 5' },
    author: { ru: 'Автор 5', en: 'Author 5' },
    year: 1995,
    cover: '/demo.webp',
  },
  {
    kind: 'game',
    title: { ru: 'Игра 6', en: 'Game 6' },
    author: { ru: 'Автор 6', en: 'Author 6' },
    year: 2000,
    cover: '/demo.webp',
  },
  {
    kind: 'game',
    title: { ru: 'Игра 7', en: 'Game 7' },
    author: { ru: 'Автор 7', en: 'Author 7' },
    year: 2005,
    cover: '/demo.webp',
  },
  {
    kind: 'game',
    title: { ru: 'Игра 8', en: 'Game 8' },
    author: { ru: 'Автор 8', en: 'Author 8' },
    year: 2010,
    cover: '/demo.webp',
  },
  {
    kind: 'book',
    title: { ru: 'Книга 1', en: 'Book 1' },
    author: { ru: 'Автор 1', en: 'Author 1' },
    year: 1975,
    cover: '/demo.webp',
  },
  {
    kind: 'book',
    title: { ru: 'Книга 2', en: 'Book 2' },
    author: { ru: 'Автор 2', en: 'Author 2' },
    year: 1980,
    cover: '/demo.webp',
  },
  {
    kind: 'book',
    title: { ru: 'Книга 3', en: 'Book 3' },
    author: { ru: 'Автор 3', en: 'Author 3' },
    year: 1985,
    cover: '/demo.webp',
  },
  {
    kind: 'book',
    title: { ru: 'Книга 4', en: 'Book 4' },
    author: { ru: 'Автор 4', en: 'Author 4' },
    year: 1990,
    cover: '/demo.webp',
  },
  {
    kind: 'book',
    title: { ru: 'Книга 5', en: 'Book 5' },
    author: { ru: 'Автор 5', en: 'Author 5' },
    year: 1995,
    cover: '/demo.webp',
  },
  {
    kind: 'book',
    title: { ru: 'Книга 6', en: 'Book 6' },
    author: { ru: 'Автор 6', en: 'Author 6' },
    year: 2000,
    cover: '/demo.webp',
  },
  {
    kind: 'book',
    title: { ru: 'Книга 7', en: 'Book 7' },
    author: { ru: 'Автор 7', en: 'Author 7' },
    year: 2005,
    cover: '/demo.webp',
  },
  {
    kind: 'book',
    title: { ru: 'Книга 8', en: 'Book 8' },
    author: { ru: 'Автор 8', en: 'Author 8' },
    year: 2010,
    cover: '/demo.webp',
  },
] satisfies Favorite[]
